#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  webapp:
    build:
      dockerfile: ./.docker/DevContainer/WebApp/Dockerfile
    environment:
      - ASPNETCORE_HTTPS_PORT=${WEB_APP_HOST_HTTPS_PORT} # So that the application's HTTP to HTTPS redirection works as intended.
      - WEATHER_FORE_CAST_API=http://webapi:5000
    volumes:
      - ./WebApp/:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - "${WEB_APP_HOST_HTTP_PORT}:5000"
      - "${WEB_APP_HOST_HTTPS_PORT}:5001"
  webapi:
    build:
      dockerfile: ./.docker/DevContainer/WebApi/Dockerfile
    environment:
      - ASPNETCORE_HTTPS_PORT=${WEB_API_HOST_HTTPS_PORT}
    volumes:
      - ./WebApi/:/workspace:cached
    command: sleep infinity
    ports:
      - "${WEB_API_HOST_HTTP_PORT}:5000"
      - "${WEB_API_HOST_HTTPS_PORT}:5001"